### ISSUE TITLE
Code is missing

### ISSUE THREAD

**Issue by geekoftheweek** [XuweiyiChen/UniCtrl#1]
FYI the readme states:

> Our code about UniCtrl is released

...but this repository contains only examples and no code as of 3/6/2024.

**Comment by XuweiyiChen** [comment]
@geekoftheweek So UniCtrl is plug-and-play to t2v models such as AnimateDiff. For example, there is a class called **AttentionControl** in the app.py under examples. That is the code corresponding to UniCtrl. We will update the ReadMe to reflect your suggestions. We believe that the code has been open-sourced on May 5th, 2024.

**Comment by GiacomoMos** [comment]
The `examples/AnimateDiff/animatediff/models` directory containing your modified AnimateDiff modules seems to be missing however, although it can be found on your huggingface repository. The code cannot be run in its current state.

**Comment by XuweiyiChen** [comment]
Please consult step 3 in the readme to download pre-trained weights, LoRA, etc.

**Comment by GiacomoMos** [comment]
I'm not referring to the `AnimateDiff/models` directory, which contains the model checkpoints. 
It's the `AnimateDiff/animatediff/models` directory (of the same name) that's missing, [here](https://huggingface.co/spaces/Xuweiyi/UniCtrl/tree/main/animatediff/models) on your huggingface, which contains your modified AnimateDiff modules. It looks like your .gitignore might be incorrect.

**Comment by XuweiyiChen** [comment]
Thanks for catching that! We accidentally removed it because of gitignore.
